### ISSUE TITLE
Problem with CreateObject("PCOMM.autECLConnList")

### ISSUE THREAD

**Issue by NavarroRamon** [dhruvinsh/ibm#1]
Hello i was checking your IBM project and i have a doubt, for some reason this part of the code 
(core file line 24 "CreateObject("PCOMM.autECLConnList")" ) 
is crashing with the next error, "OSError: [WinError -2147221164] Class not registered".
Do you know why is this happening?

**Comment by dhruvinsh** [comment]
Hi @NavarroRamon ,
Unfortunately I do not have access to the AS400 anymore. But while executing your code do you have AS400 open. Can you also provide any possible further information like, your windows environment, AS400 version, python version, dependency that you are using etc.
